#
# This file is part of the HAMMER build system.
#
# Copyright (C) 2012-2013 Aaro Koskinen <aaro.koskinen@iki.fi>
#
# Licensed under the GNU General Public License version 2 (GPLv2).
#

include Makefile.packages

packages += buildhost
packages += iself
packages += prepare

override HW_ARCH = host
override BUILD_SUBSYSTEM = utils

include ../scripts/Makefile.subsystem
